retrieved_job_application/job_application/objects/Candidate__c.object
<CustomObject>
    <description>Candidate applying for a job position</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/USA_Visa_Valid_To__c.field-meta.xml
<CustomField>
    <fullName>USA_Visa_Valid_To__c</fullName>
    <description>USA Visa Valid To</description>
    <label>USA Visa Valid To</label>
    <type>Date</type>
</CustomField>

retrieved_job_application/job_application/objects/Job_Application__c.object
<CustomObject>
    <description>Job Application of a Candidate to a particular Job Position</description>
    <fields>
        <fullName>Application_Candidate__c</fullName>
        <description>Application Candidate</description>
        <label>Application Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Application_Position__c</fullName>
        <description>Application Candidate</description>
        <label>Application Position</label>
        <referenceTo>Job_Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>USA_Visa_Holder__c</fullName>
        <defaultValue>false</defaultValue>
        <description>USA Visa Holder</description>
        <label>USA Visa Holder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>USA_Visa_Valid_To__c</fullName>
        <description>USA Visa Valid To</description>
        <label>USA Visa Valid To</label>
        <type>Date</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieved_job_application/job_application/objects/Job_Position__c.object
<CustomObject>
    <description>Job Position</description>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ukraine</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Poland</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Position</label>
    <nameField>
        <displayFormat>JP-{0000}</displayFormat>
        <label>Job Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Job_Application__c/JobApplicationHelper.cls
public with sharing class JobApplicationHelper {
  public static final String VISA_EXPIRY_ERROR_TEXT = 'You can not apply for this job due to your US visa expiration date';
  public static final Integer MIN_YEARS_TO_VISA_EXPIRY_DATE = 1;

  public static void validateUSAVisaExpiryDate(
    List<Job_Application__c> insertedJobApplications
  ) {
    Date minExpiryDate = Date.today().addYears(MIN_YEARS_TO_VISA_EXPIRY_DATE);
    Set<Id> positionIds = new Set<Id>();
    Set<Id> candidateIds = new Set<Id>();
    for (Job_Application__c jobApplication : insertedJobApplications) {
      candidateIds.add(jobApplication.Application_Candidate__c);
      positionIds.add(jobApplication.Application_Position__c);
    }

    Map<Id, Job_Position__c> positions = new Map<Id, Job_Position__c>(
      [SELECT Id, Location__c FROM Job_Position__c WHERE Id IN :positionIds]
    );

    Map<Id, Candidate__c> candidates = new Map<Id, Candidate__c>(
      [
        SELECT Id, USA_Visa_Holder__c, USA_Visa_Valid_To__c
        FROM Candidate__c
        WHERE Id IN :candidateIds
      ]
    );

    for (Job_Application__c jobApplication : insertedJobApplications) {
      Candidate__c candidate = candidates.get(
        jobApplication.Application_Candidate__c
      );
      Job_Position__c position = positions.get(
        jobApplication.Application_Position__c
      );
      if (position.Location__c == 'USA') {
        Boolean isValid =
          candidate.USA_Visa_Holder__c &&
          (candidate.USA_Visa_Valid_To__c >= minExpiryDate);
        if (!isValid) {
          jobApplication.addError(VISA_EXPIRY_ERROR_TEXT);
        }
      }
    }
  }
}