retrieved_job_application/job_application/objects/Job_Position__c.object
<CustomObject>
    <description>Job Position</description>
    <fields>
        <fullName>Candidate_Level__c</fullName>
        <inlineHelpText>Candidate Level</inlineHelpText>
        <label>Candidate Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Software Engineer</fullName>
                </value>
                <value>
                    <fullName>Senior Software Engineer</fullName>
                </value>
                <value>
                    <fullName>Lead Software Engineer</fullName>
                </value>
                <value>
                    <fullName>Junior Software Engineer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Position_Title__c</fullName>
        <inlineHelpText>Job Position Title</inlineHelpText>
        <label>Job Position Title</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ukraine</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Poland</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position_Budget__c</fullName>
        <inlineHelpText>Job Position Budget</inlineHelpText>
        <label>Position Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Practice_Unit__c</fullName>
        <description>Willing to work remote</description>
        <label>Practice Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>.Net</fullName>
                </value>
                <value>
                    <fullName>Java</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hot</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Position</label>
    <nameField>
        <displayFormat>JP-{0000}</displayFormat>
        <label>Job Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/JobPosition__c/JobPositionService.cls
public with sharing class JobPositionService {
  public static List<Job_Position__c> getJobPositions(String practiceUnit) {
    if (practiceUnit == null)
      return [
        SELECT
          Name,
          Priority__c,
          Job_Position_Title__c,
          Candidate_Level__c,
          Practice_Unit__c,
          Location__c,
          Position_Budget__c
        FROM Job_Position__c
        ORDER BY Priority__c, Name
      ];
    return [
      SELECT
        Name,
        Priority__c,
        Job_Position_Title__c,
        Candidate_Level__c,
        Practice_Unit__c,
        Location__c,
        Position_Budget__c
      FROM Job_Position__c
      WHERE Practice_Unit__c = :practiceUnit
      ORDER BY Priority__c, Name
    ];
  }
}