retrieved_job_application/job_application/objects/Job_Position__c.object
<CustomObject>
    <description>Job Position</description>
    <fields>
        <fullName>Practice_Unit__c</fullName>
        <description>Willing to work remote</description>
        <label>Practice Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>.Net</fullName>
                </value>
                <value>
                    <fullName>Java</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Position</label>
    <nameField>
        <displayFormat>JP-{0000}</displayFormat>
        <label>Job Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/JobPositionHelper.cls
public class JobPositionHelper {
    public static final String SF_JOB_POSITION_PRACTICE_UNIT = 'Salesforce';
    public static final String SF_JOB_POSITION_NAME_PREFIX = 'SF';


    public static void updateJobPositionTitle(List<Job_Position__c> insertedJobPositions) {
        for (Job_Position__c jobPosition: insertedJobPositions) {
            if (jobPosition.Practice_Unit__c == SF_JOB_POSITION_PRACTICE_UNIT) {
                jobPosition.Name = SF_JOB_POSITION_NAME_PREFIX + jobPosition.Name;
            }
        }
    }
}